version: '3'

services:
        web:
                build: .
                container_name: "php7.2"
                ports:
                - "8000:80"
                volumes:
                - ../..:/var/www/html
                - .:/code
                - ./apache-config.conf:/etc/apache2/sites-enabled/000-default.conf
        db:
                image: mysql:5.7
                environment:
                        MYSQL_ROOT_PASSWORD: my_secret_pw_shh
                        MYSQL_DATABASE: test_db
                        MYSQL_USER: devuser
                        MYSQL_PASSWORD: devpass
                ports:
                        - "9906:3306"