# This is a basic workflow to help you get started with Actions

name: Code Tests 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
            
      - name: Build containers
        run: docker-compose  -f "docker-compose.ci.yml" build
      
      - name: Run containers
        run: docker-compose  -f "docker-compose.ci.yml" up -d

      - name: Show containers
        run: docker ps -a
        
      - name: Show volumes
        run: docker volume ls

      - name: ls working directory
        run: docker-compose  -f "docker-compose.ci.yml" exec -T web ls

      - name: ls /code directory
        run: docker-compose  -f "docker-compose.ci.yml" exec -T web ls /code
          
      - name: setup laravel (cmd dosent seem to run)
        run: docker-compose  -f "docker-compose.ci.yml" exec -T web /code/setup_test_laravel.sh

      - name: setup example.com (cmd dosent seem to run)
        run: docker-compose  -f "docker-compose.ci.yml" exec -T example.com service ssh start
                 
      - name: ssh key connection setup test
        run: docker-compose -f docker-compose.ci.yml exec -T web php docker/dev/docker-tests/sshKeyConnection.php

      - name: run phpunit tests
        run: docker-compose  -f "docker-compose.ci.yml" exec -T web /var/www/html/vendor/bin/phpunit
      
      - name: run codeception tests
        run: docker-compose  -f "docker-compose.ci.yml" exec -T web /var/www/html/vendor/bin/codecept run -n

      - name: Run containers
        run: docker-compose  -f "docker-compose.ci.yml" down --volumes
